steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:465.0.0-slim'  # ✅ Pin the version
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=LANGCHAIN_TRACING_V2=true,LANGCHAIN_PROJECT=${_SERVICE_NAME}'
      - '--set-secrets=GOOGLE_API_KEY=google-api-key:latest,LANGSMITH_API_KEY=langsmith-api-key:latest'

images:
  - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}'

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/google-api-key/versions/latest
      env: 'GOOGLE_API_KEY'
    - versionName: projects/${PROJECT_ID}/secrets/langsmith-api-key/versions/latest
      env: 'LANGSMITH_API_KEY'

substitutions:
  _SERVICE_NAME: starfleet-advisor-tng
  _REGION: us-central1
